# Generated by Django 3.2.9 on 2021-11-21 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('text', models.TextField(max_length=2000, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.CharField(max_length=3, null=True)),
                ('age', models.CharField(max_length=2, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('subject', models.CharField(choices=[('1', 'angielski'), ('2', 'matematyka'), ('3', 'polski')], max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
