# Generated by Django 3.2.9 on 2021-11-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0003_reservetutoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetutoring',
            name='tutor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_ads.notice'),
        ),
    ]
