# Generated by Django 3.2.9 on 2021-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0004_alter_reservetutoring_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetutoring',
            name='accept',
            field=models.CharField(choices=[('1', 'Zaakceptuj korepetycje'), ('2', 'Odrzuć korepetycje')], max_length=200, null=True),
        ),
    ]
