# Generated by Django 3.2.9 on 2021-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0005_reservetutoring_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetutoring',
            name='accept',
            field=models.CharField(blank=True, choices=[('1', 'Zaakceptuj korepetycje'), ('2', 'Odrzuć korepetycje')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservetutoring',
            name='agree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
