# Generated by Django 3.2.9 on 2021-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0006_auto_20211124_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetutoring',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservetutoring',
            name='number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reservetutoring',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
