# Generated by Django 3.2.9 on 2021-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0007_auto_20211127_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='subject',
            field=models.CharField(choices=[('angielski', 'angielski'), ('matematyka', 'matematyka'), ('polski', 'polski')], max_length=200, null=True),
        ),
    ]
