# Generated by Django 3.2.9 on 2021-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetutoring',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
