# Generated by Django 3.2.9 on 2021-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0010_reservetutoring_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetutoring',
            name='hours',
            field=models.TimeField(null=True),
        ),
    ]
