# Generated by Django 3.2.9 on 2021-12-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0011_alter_reservetutoring_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
