# Generated by Django 3.2.9 on 2021-12-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0012_delete_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetutoring',
            name='day',
        ),
    ]
