# Generated by Django 3.2.9 on 2021-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0013_remove_reservetutoring_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetutoring',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
