# Generated by Django 3.2.9 on 2021-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0014_alter_reservetutoring_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetutoring',
            name='phone_number',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='reservetutoring',
            name='agree',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservetutoring',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservetutoring',
            name='number',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='reservetutoring',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
