# Generated by Django 3.2.9 on 2022-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_ads', '0015_auto_20211219_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
