# Generated by Django 3.2.9 on 2021-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
