# Generated by Django 3.2.9 on 2021-12-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ratingsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='admin_agree',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
