# Generated by Django 3.2.9 on 2022-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogentry_average_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='blog_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
