# Generated by Django 3.2.9 on 2021-12-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default=3, max_length=254),
            preserve_default=False,
        ),
    ]
